name: Service A CI Pipeline

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker tag
      id: version
      run: |
        export VERSION=$(grep -oP '"version":\s*"\K[0-9\.]+' package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build . -t hishmath/nest-demo-service-a:${{ env.VERSION }}

    - name: Push Docker Image
      run: |
        docker push hishmath/nest-demo-service-a:${{ env.VERSION }}

    - name: Update K8s Manifests
      run: |
        sed -i "s|image: hishmath/nest-demo-service-a:.*|image: hishmath/nest-demo-service-a:${{ env.VERSION }}|g" deployment/deploy.yaml

    - name: Commit the changes of deployment file
      run: |
        git config --global user.email "<mailtohdeen@gmail.com>"
        git config --global user.name "GitHub Actions Bot"
        git add *
        git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
        git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/Hishmathdeen/nest-demo-service-a.git
        git push origin main
